# See http://kafka.apache.org/documentation.html#api for semantics and defaults.

# Required
metadata.broker.list: localhost:9092

# Required
request.required.acks: 	1

#request.timeout.ms:

# Required
# async | sync
producer.type: 	sync

# Required
serializer.class: kafka.serializer.StringEncoder

#key.serializer.class:

#Required
partitioner.class: com.hpcloud.SimplePartitioner

#compression.codec:
#compressed.topics :
#message.send.max.retries:
#retry.backoff.ms:
#topic.metadata.refresh.interval.ms:
#queue.buffering.max.ms:
#queue.buffering.max.messages:
#queue.enqueue.timeout.ms:
#batch.num.messages:
#send.buffer.bytes:
#client.id: